### ISSUE TITLE
what is the 'configuration' file, in  'import configuration as config'

### ISSUE THREAD

**Issue by 375000384** [manurare/360monodepth#1]
hi, 
   when i study the 360monodepth source code, I can not find the 'configuration' file or can not install the module 'configuration' by 'pip install configuration'.
  need you help .
thankyou

**Comment by manurare** [comment]
Hi,

Sorry the files that have that import are not needed. They were old files that happened to be added to the repo. I have deleted them in a new commit. There should not be any file with a configuration import anymore. Let me know if this helps.

**Comment by 375000384** [comment]
This is very useful, and thank you very much



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月6日(星期五) 下午4:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [manurare/360monodepth] what is the &#39;configuration&#39; file, in  &#39;import configuration as config&#39; (Issue #1)





 
Hi,
 
Sorry the files that have that import are not needed. They were old files that happened to be added to the repo. I have deleted them in a new commit. There should not be any file with a configuration import anymore. Let me know if this helps.
