### ISSUE TITLE
Convert disparity to depth maps

### ISSUE THREAD

**Issue by hieuvmphan** [manurare/360monodepth#10]
Hi,
thanks for sharing the code.

Based on my understanding, the output `erp_dispmap_blend` of the `depth_estimation()` function is the disparity maps not the depth map.

If so, how can I convert disparity to depth and store them as pfm.

Thanks.

**Comment by cr333** [comment]
You could use these two functions:
https://github.com/manurare/360monodepth/blob/7b81bc471b3bcf4c9db4676805fe68b1a5dc5f0d/code/python/src/utility/depthmap_utils.py#L736
https://github.com/manurare/360monodepth/blob/7b81bc471b3bcf4c9db4676805fe68b1a5dc5f0d/code/python/src/utility/depthmap_utils.py#L660
