### ISSUE TITLE
Find parameters for disparity2depth

### ISSUE THREAD

**Issue by hieuvmphan** [manurare/360monodepth#11]
Hi,

I see that the function `disparity2depth()` has 2 parameters `baseline` and `focal`.

Do you know how to find these two parameters?

Since I use only a single 360 camera with Lidar to capture depths, there is no _baseline between the two cameras_.

Could you please suggest some approach to determine the baseline and focal?

**Comment by cr333** [comment]
You can use the default values provided by the function (`baseline=1` and `focal=1`), which computes depth as inverse disparity.

Please note that the depth has an arbitrary scale. If you need a different scale, you can scale it however you like.
