### ISSUE TITLE
最终得到的 DPT深度数据，怎么样转换成一个全景图片呢？

### ISSUE THREAD

**Issue by 375000384** [manurare/360monodepth#13]

**Comment by manurare** [comment]
Hey,

I am not quite sure I understand the question. The final DPT image is already a panorama (equirectangular) image. You could use [this code](https://github.com/manurare/360monodepth/blob/7b81bc471b3bcf4c9db4676805fe68b1a5dc5f0d/code/python/src/utility/depthmap_utils.py#L545) to read a dpt file from memory

**Comment by 375000384** [comment]
Thanks for you help.

Now, I have another problem when " docker build -t 360monodepth . ".   “#17 0.526 /bin/sh: 1: cd: can't cd to /monodepth/python/src/test”
----------------------------------------------------------------------------------------------------------------------------------
=> [10/12] RUN cd cpp && mkdir build && cd build && cmake ..  -DCMAKE_BUILD_TYPE=Release && make -j                                                  44.0s
 => [11/12] RUN cd cpp/python/ && python3 ./setup.py build && python3 ./setup.py bdist_wheel && pip3 install dist/instaOmniDepth-0.1.0-cp38-cp38-lin  10.3s
 => ERROR [12/12] RUN cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1                                                 0.7s
------
 > [12/12] RUN cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1:
**#17 0.526 /bin/sh: 1: cd: can't cd to /monodepth/python/src/test**
------
executor failed running [/bin/sh -c cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1]: exit code: 2

**Comment by 375000384** [comment]
Thank you .
But I I encountered another error prompt as follows, and the file test_depthmapAlign_module.py not found：
![a](https://user-images.githubusercontent.com/53556908/218003115-131d99bb-19b9-410e-823f-feb1dc10c843.png)

[12/12] RUN cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1:
#17 0.526 /bin/sh: 1: cd: can't cd to /monodepth/python/src/test
