### ISSUE TITLE
Rotation for each tangent image

### ISSUE THREAD

**Issue by jonathanventura** [manurare/360monodepth#15]
Is there an easy way to get a rotation matrix for each tangent image?  i.e. the rotation matrix between the tangent image and the panorama's coordinate system.

**Comment by manurare** [comment]
Hi,

Sorry about the delay. Yes, if you execute the main script with the flag `--intermediate_data`, we save the tangent images camera parameters. You can have access to them [here](https://github.com/manurare/360monodepth/blob/7b81bc471b3bcf4c9db4676805fe68b1a5dc5f0d/code/python/src/main.py#L290) . The variable `subimage_cam_param_list` is what you are looking for.

**Comment by jonathanventura** [comment]
Thank you!  Are these the world-to-camera rotations or camera-to-world?  Also, what is the coordinate system for the camera?  Is it with +X pointing to the right, -Y pointing up, +Z pointing out?  Or is +X right, +Y up, -Z out?

**Comment by manurare** [comment]
They are world-to-camera. And the tangent camera coordinate system is +X right, +Y up, -Z out

**Comment by jonathanventura** [comment]
Thanks!
