### ISSUE TITLE
Using ZoeDepth produce bad blending

### ISSUE THREAD

**Issue by patriciogonzalezvivo** [manurare/360monodepth#19]
I have simplify and extent this repository in [this fork](https://github.com/patriciogonzalezvivo/360monodepth/) so I can easily use it as a pipeline to extract depth from 360 photos taken with a Ricoh camera. Can't made `poisson` blending to work (https://github.com/manurare/360monodepth/issues/18) but I had success using `frustum` blending.
Here the results of the test image on `midas2` and `midas3` models
![0001_midas2_frustum](https://github.com/manurare/360monodepth/assets/346914/f827e28e-2a41-47f3-995a-224e4e419dbd)
![0001_midas3_frustum](https://github.com/manurare/360monodepth/assets/346914/e20cd2e7-aa0e-41b2-968c-1b8b68937536)
When extending the models to support [ZoeDepth](https://github.com/isl-org/ZoeDepth) motivated by their spatial consistency the results seams to have blending issues. 
![0001_zoedepth_frustum](https://github.com/manurare/360monodepth/assets/346914/84afe18e-3da1-4f08-8225-82e2b3fbc5ee)

Wonder if the approach I'm using is the correct, and if there is something else I should be doing?

**Comment by manurare** [comment]
Hi,

Haven't tried ZoeDepth myself. Are you sure that the output depthmaps are predicted up to an unknown offset and scale factor as in midas? Is there any other unknown factor reported in the paper that might be required to be optimized for in the deformable alignment?

**Comment by patriciogonzalezvivo** [comment]
Great point! zoedepth model try to make a metric estimation, so unlike MiDAS lower values means closer. I flip (and scale) the values when the depth estimations are generated and that solved the issue. Thank you!

![0001_zoedepth_frustum](https://github.com/manurare/360monodepth/assets/346914/d994e86b-4177-4a6c-92b1-37b2d6dd0f15)
