### ISSUE TITLE
How to have access to the depth map

### ISSUE THREAD

**Issue by navid-mahmoudian** [manurare/360monodepth#2]
Hello,

Thank you very much for this nice library. Could you please let me know how I can access the output depth map? When I run your code on an unseen equirectangular RGB image, I get five images as follows:
`000_360monodepth_midas2_frustum.png`, `000_360monodepth_midas2_mean.png`, `000_360monodepth_midas2_nn.png`, `000_360monodepth_midas2_poisson.png`, `000_360monodepth_midas2_radial.png`

However, I would like to generate the point cloud from the output of your program to see how the depth prediction works visually.

**Comment by manurare** [comment]
Hi,

[```estimated_depthmap```](https://github.com/manurare/360monodepth/blob/43347063f1fa521ea3e0866ff85bbcb734b64393/code/python/src/main.py#L486) are the raw depth predictions before being saved. You can manipulate those np arrays to generate the point cloud
