### ISSUE TITLE
python module not installed

### ISSUE THREAD

**Issue by antithing** [manurare/360monodepth#20]
Hi, and thanks for this code! I have it built, and when running main.py I see this error:

`2024-04-02 17:55:43,282 - utility.depthmap_align - ERROR - depthmapAlign python module do not install, please build and install it reference the readme.`

Can you please point me at the instructions for this?

I have built in visual studio successfully.

**Comment by antithing** [comment]
EDIT, I have run the setup.py correctly, and now I see:
```

(360monodepth) C:\\tools\NeuralDOF\360monodepth\code\python\src>python main.py --expname test_experiment --blending_method all --grid_size 8x7
Adding 'C:\\tools\NeuralDOF\360monodepth\code\python\src' to sys.path
2024-04-03 13:58:46,963 - utility.depthmap_align - INFO - depthmapAlign python module installed!
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    from utility import blending
  File "C:\\tools\NeuralDOF\360monodepth\code\python\src\utility\blending.py", line 6, in <module>
    from EigenSolvers import LinearSolver
ModuleNotFoundError: No module named 'EigenSolvers'
```

I have the EigenSolvers pyd built, What do I do with it?

**Comment by manurare** [comment]
Hello,

After building, you should have generated the library `EigenSolvers.cpython-38-x86_64-linux-gnu.so` under `code/cpp/lib`. When you run `main.py`, at the beginning of the file, it imports some modules from `utility`. `utility.__init__` adds  `code/cpp/lib` to sys.path and EigenSolvers should be found. 

Another option is first
`from instaOmniDepth import depthmapAlign`
and afterwards add:
`from instaOmniDepth import EigenSolvers`
