### ISSUE TITLE
EigenSolvers import error

### ISSUE THREAD

**Issue by dbotsriram** [manurare/360monodepth#22]
![Screenshot from 2024-05-20 18-33-29](https://github.com/manurare/360monodepth/assets/168647369/1e39885d-20ca-4f9f-b590-b471d60cac67)

While running python main.py --expname test_experiment --blending_method all --grid_size 8x7 
I'm getting ImportError: /home/dbot/Desktop/360monodepth/360monodepth/code/cpp/lib/EigenSolvers.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN6google10LogMessage6streamEv

Please help me with this

**Comment by TingtingLiao** [comment]
https://github.com/manurare/360monodepth/blob/21bd0bcf634759cf6378cef59e97c98e3d83ee83/code/cpp/CMakeLists.txt#L199 

```
target_link_libraries(EigenSolvers PRIVATE ${GLOG_LIBRARIES})
#target_link_libraries(EigenSolvers PRIVATE glog::glog)
```

change this to 
```
#target_link_libraries(EigenSolvers PRIVATE ${GLOG_LIBRARIES})
target_link_libraries(EigenSolvers PRIVATE glog::glog)
```
and reinstall

**Comment by dbotsriram** [comment]
Thank you @TingtingLiao  The issue had been solved
