### ISSUE TITLE
About Dpt File

### ISSUE THREAD

**Issue by Ferdeno** [manurare/360monodepth#24]
1. Is the [0001_depth.dpt] file created at runtime or should it be provided as input?

2. Could anyone provide information about the .dpt file used here?

3. Should the .dpt file be provided as input along with the 360 image, or is the 360 image alone sufficient?

your insights are greatly appreciated 

![image](https://github.com/manurare/360monodepth/assets/125113134/da702b3f-9064-4f9b-8fdf-aab4623c1b41)

**Comment by manurare** [comment]
If you dont have ground-truth dpt then you should follow the README [here](https://github.com/manurare/360monodepth?tab=readme-ov-file#data)
