### ISSUE TITLE
Killed while running with different input

### ISSUE THREAD

**Issue by Ferdeno** [manurare/360monodepth#25]
When i give different input without GT and None in second coloumn of the .txt file. It gives a killed command in terminal 
Please help me with this.

![WhatsApp Image 2024-05-24 at 18 22 00](https://github.com/manurare/360monodepth/assets/125113134/6662eef8-fadf-45e0-afd5-99fc6e1df803)

**Comment by Ferdeno** [comment]
@manurare Could you please help me with this issue?

**Comment by manurare** [comment]
Hi,

For me it works. Maybe try to delete the `None` column and just write a single column with the rgb file path

**Comment by Ferdeno** [comment]
Hi, 

Your Code is working for the input data and I'm getting the depth map,
The solution for the issue that I had faced is changing the input image dimensions as your code accepts the image that has 2k resolution but i gave more than 2k resolution so the issue araises.

and 

While giving None or empty in the second column in the txt file i got a error 

Traceback (most recent call last):
  File "main.py", line 563, in <module>
    monodepth_360(opt)
  File "main.py", line 498, in monodepth_360
    serialization.save_predictions(output_folder, erp_gt_depthmap, erp_rgb_image_data, estimated_depthmap,
  File "/home/dbot/Desktop/360monodepth/360monodepth/code/python/src/utility/serialization.py", line 358, in save_predictions
    plt.imsave(os.path.join(output_folder, "{:03}_GT.png".format(idx)),
  File "/home/dbot/anaconda3/envs/360monodepth/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2200, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/home/dbot/anaconda3/envs/360monodepth/lib/python3.8/site-packages/matplotlib/image.py", line 1658, in imsave
    pil_shape = (rgba.shape[1], rgba.shape[0])
AttributeError: 'tuple' object has no attribute 'shape'


![Screenshot from 2024-05-31 10-56-18](https://github.com/manurare/360monodepth/assets/125113134/7fdedc74-d43c-4149-9fda-9cb0cf9ce0ff)


With Dpt file the output folder has the following files

![Screenshot from 2024-05-31 11-15-15](https://github.com/manurare/360monodepth/assets/125113134/955cdf78-cbd0-4745-9064-b48f999f110f)

Without Dpt file the output folder has the following files

![Screenshot from 2024-05-31 11-16-28](https://github.com/manurare/360monodepth/assets/125113134/1c4e42c3-bf34-4d72-b2a5-a954f5a38f3f)


What kind of error is this?

**Comment by manurare** [comment]
It looks like what you are trying to save is not an array.

For the second question, if there is no GT we save disparity, if there is GT we save depth
