### ISSUE TITLE
point_clouds

### ISSUE THREAD

**Issue by hcscysh** [manurare/360monodepth#26]
Thank you for your great work.when I use depth map and rgb to genetate point clouds,in one scene,there are many points,how I process all point clouds to genetate a Integral point clound.In the website, I see a example, x = np.array([0, 0, 0)
x_prime = r @ x + c,but the final point cloud is chaotic.

**Comment by manurare** [comment]
Hey, 

Make sure that the rotation and C you are using refer to cam2world rotation and translation. Otherwise, it could be that the depthmap looks great but it is not geometrically accurate
