### ISSUE TITLE
Assertion arisen at blendIt.compute_linear_system_matrices 

### ISSUE THREAD

**Issue by kaimw** [manurare/360monodepth#27]
Hi, thanks for the excellent work. I have successfully built the project. However, when running the example data,  program crashed and an assertion have arisen as follow:

`
python: /usr/include/eigen3/Eigen/src/SparseCore/SparseMatrix.h:396: Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::Scalar& Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::insertBackByOuterInner(Eigen::Index, Eigen::Index) [with _Scalar = double; int _Options = 0; _StorageIndex = int; Eigen::SparseMatrix<_Scalar, _Flags, _StorageIndex>::Scalar = double; Eigen::Index = long int]: Assertion (m_outerIndex[outer+1]-m_outerIndex[outer]==0 || m_data.index(m_data.size()-1)<inner) && "Invalid ordered insertion (invalid inner index)"' failed.
`

at step : # 4) blender to ERP image & output ERP disparity map and visualized image
![image](https://github.com/manurare/360monodepth/assets/5046477/d4f9f912-e269-49c0-86a7-cfdbed0103e1)

![image](https://github.com/manurare/360monodepth/assets/5046477/b650e6a6-9a5b-4410-87f6-a680e94b8605)

How can I solve this problem

**Comment by manurare** [comment]
Hi. Never seen this error before. Maybe you are using a different version of Eigen?

**Comment by kaimw** [comment]
> Hi. Never seen this error before. Maybe you are using a different version of Eigen?

It's fixed since I changed eigen version from  3.4.0 to 3.3.9.

Thanks for your replay.
