### ISSUE TITLE
grayscale type prosessing

### ISSUE THREAD

**Issue by hahakmj** [manurare/360monodepth#29]
Hello, I am impressed with your idea. Thank you.
However, I want to extract a grayscale depth map for a feel similar to Facebook 3D photos. When generating depth maps based on MiDas, I easily obtained the desired data by using the '--grayscale' option in the command. I'm curious how to achieve this result with 360monodepth.

**Comment by manurare** [comment]
Hi,

you can convert the [output of the pipeline](https://github.com/manurare/360monodepth/blob/5c053f2285466cb884d148dc54489ec654327668/code/python/src/main.py#L489) to grayscale using your favourite image processing library
