### ISSUE TITLE
Increase number of images step 1

### ISSUE THREAD

**Issue by shreyask3107** [manurare/360monodepth#3]
Hi @manurare, currently the model takes 20 images from the faces of an icosahedron. 
Could you recommend me ways in which I can increase the number of images (close to 100 or 200) and the code to do the same?

I am aware that project_icosahedron.py implements the required projections. More details will be super helpful.
Thanks!

**Comment by manurare** [comment]
Hi,

You can always subdivide further the icosahedron. One way is to find the barycentric coordinates for each face, and form new smaller faces by joining every vertex of a face with the barycentric center. This will create 3 smaller faces per initial face of the icosahedron ending up with a finer subdivision with 60 faces. If you want even more, you can subdivide further or I found that [the Fibonacci sphere algorithm](https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere) is a good way for defining a regular grid over a sphere.

As long as the function for creating more images returns the same kind of data as [`get_icosahedron_parameters`](https://github.com/manurare/360monodepth/blob/43347063f1fa521ea3e0866ff85bbcb734b64393/code/python/src/utility/projection_icosahedron.py#L21), there should not be any problem.

**Comment by shreyask3107** [comment]
Hi @manurare , Thank You very much.
I will try to implement this👍

I will keep this issue open for a couple of days if I face any issues in implementing Fibonacci Sphere algorithm.

**Comment by shreyask3107** [comment]
Hi @manurare , even with the Fibonacci Sphere Algorithm, I shall only get the tangent points. 
How would you recommend me to generate the triangle tangent points? 
Than You.

**Comment by manurare** [comment]
Right, now you don't have a regular polygon anymore nor exact knowledge of where each vertex of the triangle falls. What I'd do is, in each tangent point sample a tangent image using gnomonic projection. You can control how big/small your tangent plane is using `padding` or `coord_gnom_xy_range` in `gnomonic2pixel` function.
