### ISSUE TITLE
Docker Environment problem

### ISSUE THREAD

**Issue by jiayaozhang** [manurare/360monodepth#4]
Hi, nice to see your interesting work

I have problems to run your docker environment on Ubuntu 20.04 and Windows 10

Can you help to test whether the docker environment is valid or not

Thanks a lot !

**Comment by manurare** [comment]
Hi,

Which errors do you have?

**Comment by jiayaozhang** [comment]
![Screenshot from 2022-07-24 22-32-37](https://user-images.githubusercontent.com/38579506/180651880-ea4615c0-65aa-4843-ae61-779faeb29a89.png)


Attached my errors.


I found the solution from here. And here need your help to modify the docker environment


`https://stackoverflow.com/questions/39518377/docker-build-unable-to-fetch-archives`

![Screenshot from 2022-07-24 22-34-47](https://user-images.githubusercontent.com/38579506/180651957-3fb51f05-17c4-4a6e-bba6-ee0eaccd336d.png)

**Comment by manurare** [comment]
If you add that line to the `Dockerfile` does it work?

**Comment by jiayaozhang** [comment]
I change the docker file to 

`#-- setup building environment `
`RUN apt-get update  && \`
`    apt-get install -y wget && \`
`    rm -rf /var/lib/apt/lists`

Attached the results I have got

![Screenshot from 2022-07-25 18-29-00](https://user-images.githubusercontent.com/38579506/180756507-045aa87c-a3f8-4310-95d0-206d2ff29edb.png)

**Comment by manurare** [comment]
I tried `docker build -t 360monodepth .` with Docker version 20.10.16 and it works fine with me. You might need to delete the last two lines of the Dockerfile. It is not required anymore as there is no test script in the most recent version of the repo
 ```
# 3) run test script
RUN cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1
```

**Comment by jiayaozhang** [comment]
![ok](https://user-images.githubusercontent.com/38579506/181682017-6e1de4e0-cab2-4157-a5ea-34fcc476a8bd.png)


Docker runs successfully! 

Got the problem

It was because the VPN problem

**Comment by jiayaozhang** [comment]
But after I got the docker, I still can not run it.


`docker run -it --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 360monodepth "cd /monodepth/python/src; python main.py --expname test_experiment --blending_method all --grid_size 8x7"`

I can not run on host machine and docker 

And there is not python inside image..

I have never heard `NVIDIA_VISIBLE_DEVICES`, is this `CUDA_VISIBLE_DEVICES`?

**Comment by manurare** [comment]
No, `NVIDIA_VISIBLE_DEVICES` is a command specific to docker. If you have a version of Docker >=19.03 you can use [this other option](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html#gpu-enumeration) as an alternative to `NVIDIA_VISIBLE_DEVICES`

> And there is not python inside image..

This is weird. In the `Dockerfile` this line should install python. 
```
RUN apt install --no-install-recommends \
        libpython3-dev \
        python3-pip -y
```
Which error are you actually getting?

**Comment by jiayaozhang** [comment]
Now I made the codes running successful !

Attach my modifications


1. inside the docker `pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
`

2. `python3 main.py  ` not `python main.py`

3. `sudo docker run -it -v /home/janice/Documents/360monodepth/data:/data --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0  360monodepth`

4.Add  `torch.hub._validate_not_a_forked_repo=lambda a,b,c: True`

in the `depthmap_utils.py` line 183 before `midas = torch.*******************`


After running I got this result

My question is 
![Screenshot from 2022-08-02 17-18-49](https://user-images.githubusercontent.com/38579506/182339981-d51fc290-059a-4d0d-b370-4ade88c435c1.png)


How I can get the depth images from panorama images not the comparision matrix.txt

Thanks !

for exapmle, the how to make the figure and `run plot_figure.py`?

**Comment by jiayaozhang** [comment]
I got the results here!

* in main.py with line 102 and line 103
* `--rm_debug_folder` set `false`
* `--intermedia_data` set `false`
