### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by pablodawson** [manurare/360monodepth#6]
Hello,

When running Docker I run into this error:

 > [12/12] RUN cd /monodepth/python/src/test && python3 ./test_depthmapAlign_module.py --task 1:
#16 0.278 /bin/sh: 1: cd: can't cd to /monodepth/python/src/test

I'm not well versed in Docker, but seems like it's referencing a directory that's not there. What can I do?

**Comment by manurare** [comment]
Hi,

You can get rid of that line on the `Dockerfile`. This was from an old version of the code and I forgot to update it.

**Comment by pablodawson** [comment]
Thanks!
