### ISSUE TITLE
How to have access to the .dpt depth files?

### ISSUE THREAD

**Issue by jianwu-buaa** [manurare/360monodepth#7]
Hello, 

Thanks to the very nice 360 RGBD datasets! I'm struggling with using the .dpt files...Don't know how to open it and get the depth numbers. 

Could you give an example code for reading in the .dpt file?

Thank you.

**Comment by manurare** [comment]
Hi,

You can find the code here
https://github.com/manurare/360monodepth/blob/7b81bc471b3bcf4c9db4676805fe68b1a5dc5f0d/code/python/src/utility/depthmap_utils.py#L545

**Comment by jianwu-buaa** [comment]
Thank you！

I will try them in my project.
