### ISSUE TITLE
Unknown runtime specified nvidia.

### ISSUE THREAD

**Issue by ben-morrissey** [manurare/360monodepth#8]
Hello,

The result of your program looks amazing, I am trying to run the code myself to take a live look but when I try to run the code after the docker builds successfully it provides me this error:
`docker: Error response from daemon: Unknown runtime specified nvidia.`

I then modified the docker run command to use the `--gpus all` instead of the `--runtime=nvidia` command, this got me a little further however I still get a `NVIDIA GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation` error.

Am I doing something wrong, do you have any advice?

Thank you.

**Comment by pablodawson** [comment]
I had the same problem.
Just entered the docker container terminal and installed torch again: `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`
Then ran "setup.py" in the same container and worked.

**Comment by manurare** [comment]
Hi. Try to install a new version of pytorch as indicated by @pablodawson

**Comment by ben-morrissey** [comment]
Thank you so much for your help, I tried the suggestion provided however unfortunately it did not work.

I however found that what I needed to do was to install pytorch using the command below:
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f [https://download.pytorch.org/whl/torch_stable.html`](https://download.pytorch.org/whl/torch_stable.html%60)

I also used `trust_repo=True` to the `midas = torch.hub.load` call on line 190, 192, 195 and 197 of the python file [360monodepth/code/python/src/utility/depthmap_utils.py](https://github.com/manurare/360monodepth/blob/main/code/python/src/utility/depthmap_utils.py) to supress a warning about an untrusted repo.

Lastly I added `add torch.hub._validate_not_a_forked_repo=lambda a,b,c: True` to line 189 (above the calls to torch.hub.load) in the file [360monodepth/code/python/src/utility/depthmap_utils.py](https://github.com/manurare/360monodepth/blob/main/code/python/src/utility/depthmap_utils.py) to stop a 403 error I would get from the pytorch calls.

Thank you again so much for your help with this. I really appreciate it.
