### ISSUE TITLE
Fine-tune/train model on custom dataset

### ISSUE THREAD

**Issue by hieuvmphan** [manurare/360monodepth#9]
Hi,
I want to fine-tune or train the model on the custom dataset.

Could you please give some guidance?

Thanks,
Hieu

**Comment by manurare** [comment]
Hello,

Our method has not been train in any dataset. We use pre-trained MiDaS as perspective monocular depth estimator. If you want, you could fine-tune MiDaS in your own dataset. Make sure though that MiDaS is designed for perspective images so, if you have 360 images to train you would need to extract perspective images from those.
